image:
  service:
    url: http://localhost:8080
  
logging:
  level:
    root: 'off'

spring:
  main:
    banner-mode: 'off'
    web-application-type: 'NONE'
  shell:
    history:
      enabled: 'false'
  threads:
    virtual:
      enabled: true  
  jackson:
    use-jackson2-defaults: true